version: "2.2"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    network_mode: host
#    networks:
#      - backend
#    depends_on:
#      keycloak:
#        condition: service_healthy
#    links:
#      - keycloak
#  keycloak:
#    image: jboss/keycloak:7.0.0
#    ports:
#      - "8080:8080"
#    networks:
#      - backend
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
#      KEYCLOAK_IMPORT: /tmp/one-realm.json,/tmp/two-realm.json
#    volumes:
#      - "./etc/realms:/tmp"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/one"]
#      interval: 30s
#      timeout: 10s
#      retries: 7
#networks:
#  backend:
#    driver: bridge